// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'userdata.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$UserdataImpl _$$UserdataImplFromJson(Map<String, dynamic> json) =>
    _$UserdataImpl(
      id: json['id'] as String?,
      firstName: json['first_name'] as String?,
      lastName: json['last_name'] as String?,
      phone: json['phone'] as String?,
      countryCode: json['country_code'] as String?,
      phoneSecondary: json['phone_secondary'],
      userEmail: json['user_email'] as String?,
      email: json['email'] as String?,
      gender: json['gender'] as String?,
      place: json['place'] as String?,
      roleId: json['role_id'] as String?,
      roleLabel: json['role_label'] as String?,
      deviceId: json['device_id'] as String?,
      status: json['status'] as String?,
      courseId: json['course_id'] as String?,
      courseName: json['course_name'] as String?,
      courseType: json['course_type'] as String?,
      image: json['image'] as String?,
      androidVersion: json['android_version'],
      deviceIdMessage: json['device_id_message'] as String?,
      noCourseText: json['no_course_text'] as String?,
      noCourseImage: json['no_course_image'] as String?,
      contactEmail: json['contact_email'] as String?,
      contactPhone: json['contact_phone'] as String?,
      contactWhatsapp: json['contact_whatsapp'] as String?,
      contactAddress: json['contact_address'] as String?,
      contactAbout: json['contact_about'] as String?,
      zoomId: json['zoom_id'] as String?,
      zoomPassword: json['zoom_password'] as String?,
      zoomApiKey: json['zoom_api_key'] as String?,
      zoomSecretKey: json['zoom_secret_key'] as String?,
      zoomWebDomain: json['zoom_web_domain'] as String?,
      token: json['token'] as String?,
      privacyPolicy: json['privacy_policy'] as String?,
      privacyPolicyText: json['privacy_policy_text'] as String?,
      coins: (json['coins'] as num?)?.toInt(),
    );

Map<String, dynamic> _$$UserdataImplToJson(_$UserdataImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'first_name': instance.firstName,
      'last_name': instance.lastName,
      'phone': instance.phone,
      'country_code': instance.countryCode,
      'phone_secondary': instance.phoneSecondary,
      'user_email': instance.userEmail,
      'email': instance.email,
      'gender': instance.gender,
      'place': instance.place,
      'role_id': instance.roleId,
      'role_label': instance.roleLabel,
      'device_id': instance.deviceId,
      'status': instance.status,
      'course_id': instance.courseId,
      'course_name': instance.courseName,
      'course_type': instance.courseType,
      'image': instance.image,
      'android_version': instance.androidVersion,
      'device_id_message': instance.deviceIdMessage,
      'no_course_text': instance.noCourseText,
      'no_course_image': instance.noCourseImage,
      'contact_email': instance.contactEmail,
      'contact_phone': instance.contactPhone,
      'contact_whatsapp': instance.contactWhatsapp,
      'contact_address': instance.contactAddress,
      'contact_about': instance.contactAbout,
      'zoom_id': instance.zoomId,
      'zoom_password': instance.zoomPassword,
      'zoom_api_key': instance.zoomApiKey,
      'zoom_secret_key': instance.zoomSecretKey,
      'zoom_web_domain': instance.zoomWebDomain,
      'token': instance.token,
      'privacy_policy': instance.privacyPolicy,
      'privacy_policy_text': instance.privacyPolicyText,
      'coins': instance.coins,
    };
